import { defineConfig } from 'wxt'

// WXT auto-derives most of the manifest from the entrypoints/ directory:
//   - entrypoints/background.ts        → background (SW on Chrome, scripts on FF)
//   - entrypoints/relay.content.ts     → content_scripts (matches set in the file)
//   - entrypoints/popup/index.html     → action.default_popup
//   - entrypoints/options/index.html   → options_ui
//
// We only declare what WXT can't infer: permissions and the optional host
// patterns. There are no static host_permissions; concrete hosts are requested
// per printer at add-time.
export default defineConfig({
  srcDir: '.',
  // Compile JSX to our tiny `el`/`Fragment` DOM factory (see src/ui/dom.ts).
  vite: () => ({
    esbuild: { jsxFactory: 'el', jsxFragment: 'Fragment' },
  }),
  // The Firefox (AMO) sources zip must be buildable, and the extension depends
  // on the workspace package @tibordp/prusalink-bridge. So zip the whole
  // monorepo (root lockfile + packages/client + extension) rather than just the
  // extension dir; a reviewer runs `pnpm install && pnpm build:firefox`.
  zip: {
    // From the monorepo root, WXT includes git-tracked files (so build
    // artifacts like packages/client/dist stay out). Only BUILD.md needs an
    // explicit add since it may not be committed when the zip is produced.
    sourcesRoot: '..',
    // BUILD.md isn't committed when the zip runs; test files are excluded by
    // WXT's defaults but we want reviewers to be able to run them.
    includeSources: ['BUILD.md', '**/*.test.ts'],
    excludeSources: [
      '**/node_modules/**',
      'extension/.output/**',
      'extension/.wxt/**',
      '**/*.zip',
      // build artifact — regenerated by `pnpm build:firefox`
      'packages/client/dist',
      'packages/client/dist/**',
    ],
  },
  manifest: ({ browser }) => ({
    name: 'Bridge for PrusaLink',
    // Keep this honest about affiliation — it shows in the store and the
    // extensions list. (Manifest descriptions are capped at 132 chars.)
    description:
      'Send jobs to your own PrusaLink printers from web apps you trust. Unofficial — not affiliated with Prusa Research.',
    // Only `storage`. We reply to pages with tabs.sendMessage(sender.tab.id, …),
    // which needs neither the `tabs` permission (we never read url/title) nor a
    // host permission (it targets our own declared content script).
    permissions: ['storage'],
    // On Firefox, host patterns live under optional_permissions instead.
    ...(browser === 'firefox'
      ? { optional_permissions: ['http://*/*', 'https://*/*'] }
      : { optional_host_permissions: ['http://*/*', 'https://*/*'] }),
    action: { default_title: 'Bridge for PrusaLink' },
    // Firefox needs an explicit add-on id for stable storage / permissions.
    // AMO also requires every new add-on to declare what user data it collects;
    // we collect none, so the data_collection_permissions are `none`.
    ...(browser === 'firefox'
      ? {
          browser_specific_settings: {
            gecko: {
              id: 'prusalink-bridge@tibordp.github.io',
              data_collection_permissions: { required: ['none'] },
            },
          },
        }
      : {}),
  }),
})
